sudo: required
language: java
addons:
  apt:
    packages:
      - oracle-java8-installer
services:
  - docker
after_success:
  - docker build -t warproject .
  - pip install --user awscli
  - eval $(aws ecr get-login --region us-east-1)
  - export PATH=$PATH:$HOME/.local/bin
  - docker tag warproject:latest 556771014529.dkr.ecr.us-east-1.amazonaws.com/warproject:latest
  - docker push 556771014529.dkr.ecr.us-east-1.amazonaws.com/warproject:latest
