sudo: required
language: java
addons:
  apt:
    packages:
      - oracle-java8-installer
services:
  - docker
after_success:
  - docker build -t jeid/warproject .
  - docker push 
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
